version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fashion_recommender_db
    environment:
      POSTGRES_DB: fashion_recommender
      POSTGRES_USER: fashion_user
      POSTGRES_PASSWORD: fashion_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 